# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WPSEmXuIfAhcytPzL-3CRm6TbUJb1CnC
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
from io import BytesIO

st.set_page_config(page_title="Delivery Delay Predictor", layout="wide")

st.title("📦 Delivery Delay Prediction (Streamlit)")
st.caption("Upload your CSV → model predicts delivery delay → download results.")

@st.cache_resource
def load_model(model_path: str):
    return joblib.load(model_path)

def to_csv_download(df: pd.DataFrame) -> bytes:
    return df.to_csv(index=False).encode("utf-8")

# ---- Sidebar ----
st.sidebar.header("⚙️ Settings")
model_file = st.sidebar.text_input("Model file name", value="DD_Pawan.joblib")
target_col = st.sidebar.text_input("Target column (if present in CSV, will be ignored)", value="delivery_delay")

st.sidebar.markdown("---")
st.sidebar.write("Place the model file in the same repo folder as `app.py`.")

# ---- Load model ----
try:
    model = load_model(model_file)
    st.success(f"Model loaded: `{model_file}`")
except Exception as e:
    st.error(
        "❌ Could not load the model.\n\n"
        "Most common reason: wrong `numpy/scikit-learn` versions on Streamlit Cloud.\n"
        "Use the `requirements.txt` given below.\n\n"
        f"Error: {e}"
    )
    st.stop()

# ---- Upload CSV ----
uploaded = st.file_uploader("Upload your input CSV (features only, or features + target column)", type=["csv"])

if uploaded is None:
    st.info("Upload a CSV to start predictions.")
    st.stop()

# ---- Read data ----
try:
    df = pd.read_csv(uploaded)
except Exception as e:
    st.error(f"❌ Failed to read CSV: {e}")
    st.stop()

st.subheader("🔎 Uploaded data preview")
st.dataframe(df.head(20), use_container_width=True)

# ---- Prepare features ----
X = df.copy()
if target_col in X.columns:
    X = X.drop(columns=[target_col])

# Handle common bad columns (optional)
# If you trained with a full preprocessing pipeline, you usually shouldn't touch columns.
# But we’ll replace inf with NaN to avoid crashes.
X = X.replace([np.inf, -np.inf], np.nan)

# ---- Predict ----
st.subheader("✅ Predictions")

try:
    # If your model is a pipeline, this will work directly on DataFrame
    preds = model.predict(X)
except Exception as e:
    st.error(
        "❌ Prediction failed.\n\n"
        "Common reasons:\n"
        "1) CSV columns don't match training columns\n"
        "2) Missing required columns\n"
        "3) Wrong data types\n\n"
        f"Error: {e}"
    )
    st.stop()

# Create output
out = df.copy()
out["delay_prediction"] = preds

# If model supports predict_proba (classification), show probabilities too
if hasattr(model, "predict_proba"):
    try:
        proba = model.predict_proba(X)
        # Add max probability as confidence
        out["prediction_confidence"] = np.max(proba, axis=1)
    except Exception:
        pass

st.dataframe(out.head(50), use_container_width=True)

# ---- Download results ----
st.download_button(
    label="⬇️ Download predictions CSV",
    data=to_csv_download(out),
    file_name="delivery_delay_predictions.csv",
    mime="text/csv",
)